version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.12  # Use the latest Python image
    steps:
      - checkout
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Install PDM
          command: pip install pdm
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run flake8
          command: pdm run flake8
      - run:
          name: Run black
          command: pdm run black --check .
      - run:
          name: Run tests
          command: |
            pdm run pytest tests/

workflows:
  build_and_test:
    jobs:
      - build
